# Generated by Django 2.0.5 on 2018-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distortions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distortiontype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
