# Generated by Django 2.0.5 on 2018-08-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distortions', '0003_distortiontype_description'),
    ]

    operations = [
        migrations.RenameModel('DistortionType', 'TrapType')
    ]
