# Generated by Django 2.0.5 on 2018-08-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distortions', '0005_auto_20180802_1718'),
    ]

    operations = [
        migrations.RenameModel('IdentifiedTrap', 'TrapLog'),
        migrations.RenameField('TrapLog', 'caught_at', 'log_time'),
        migrations.RenameField('TrapLog', 'distortion_type', 'trap_type'),
    ]
